apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::163001231298:role/eksctl-EKS-cluster-1-nodegroup-sc-NodeInstanceRole-O1K299047AOI
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::163001231298:role/eksctl-EKS-cluster-1-nodegroup-sc-NodeInstanceRole-1OBCD84ZLG1Z1
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::163001231298:role/eksctl-EKS-cluster-1-nodegroup-sc-NodeInstanceRole-40Q8QL74W4VX
      username: system:node:{{EC2PrivateDNSName}}
kind: ConfigMap
metadata:
  creationTimestamp: "2023-04-20T07:55:06Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "27115"
  uid: 303d5496-e67e-4272-89b2-809248da0f98
